const PDFDocument = require('pdfkit');

function generateExecutiveReport(scan, res) {
    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // --- Header ---
    doc.fontSize(24).font('Helvetica-Bold').text('ADA Compliance Executive Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).font('Helvetica').text(`Scan target: ${scan.url}`, { align: 'center', color: '#666' });
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center', color: '#666' });
    doc.moveDown(2);

    // --- Score Section ---
    doc.rect(50, 130, 510, 80).fill('#f7fafc');

    // Score Circle Logic (Simplified for PDFKit)
    const scoreColor = scan.score >= 90 ? '#48bb78' : scan.score >= 50 ? '#ecc94b' : '#f56565';
    doc.save();
    doc.circle(100, 170, 30).fill(scoreColor);
    doc.fillColor('white').fontSize(18).text(scan.score, 85, 163, { width: 30, align: 'center' });
    doc.restore();

    // Metrics
    doc.fillColor('#2d3748').fontSize(14).text('Overall Compliance Score', 150, 150);
    doc.fontSize(10).text('Based on WCAG 2.1 AA Standards', 150, 170);

    doc.text(`Total Issues: ${scan.total_issues}`, 350, 150);
    doc.text(`Errors: ${scan.errors}`, 350, 165);
    doc.text(`Warnings: ${scan.warnings}`, 350, 180);

    doc.moveDown(6);


    // --- Top Issues ---
    doc.fillColor('#1a202c').fontSize(18).text('Top Compliance Violations');
    doc.moveDown();

    const topIssues = scan.detailedIssues.slice(0, 5);
    topIssues.forEach((issue, index) => {
        doc.fillColor('#2d3748').fontSize(12).font('Helvetica-Bold').text(`${index + 1}. ${issue.code}`);
        doc.font('Helvetica').fontSize(10).text(issue.message, { width: 450 });
        doc.fillColor('#718096').text(`Impact: ${issue.impact.toUpperCase()} | Occurrences: ${issue.count}`);
        doc.moveDown();
    });

    // --- Footer ---
    doc.moveDown(2);
    doc.fontSize(10).fillColor('#718096').text('Generated by ADA Compliance Scanner Pro', { align: 'center' });

    doc.end();
}

function generateCrawlReport(crawl, scans, res) {
    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // Title
    doc.fontSize(24).font('Helvetica-Bold').text('Digital Accessibility Compliance Report', { align: 'center' });
    doc.fontSize(14).text('Executive Summary', { align: 'center' });
    doc.moveDown();

    // Meta
    doc.fontSize(12).font('Helvetica').text(`Domain: ${crawl.domain}`);
    doc.text(`Total Pages Audited: ${scans.length}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    // --- High Level Summary ---
    const totalErrors = scans.reduce((sum, s) => sum + s.errors, 0);
    const avgScore = Math.round(scans.reduce((sum, s) => sum + s.score, 0) / (scans.length || 1));

    doc.rect(50, 180, 510, 100).fill('#edf2f7');
    doc.fillColor('#2d3748');

    doc.fontSize(12).text('Portfolio Health Score', 70, 200);
    doc.fontSize(30).font('Helvetica-Bold').text(avgScore, 70, 220);

    doc.fontSize(12).font('Helvetica').text('Total Critical Errors', 300, 200);
    doc.fontSize(30).font('Helvetica-Bold').text(totalErrors, 300, 220);

    doc.moveDown(6);

    // --- Worst Offenders ---
    doc.font('Helvetica-Bold').fontSize(16).text('Top 5 At-Risk Pages');
    doc.moveDown();

    const worstPages = [...scans].sort((a, b) => a.score - b.score).slice(0, 5);

    worstPages.forEach(page => {
        doc.fillColor('#c53030').fontSize(12).text(`[Score: ${page.score}] ${new URL(page.url).pathname}`);
        doc.fillColor('#4a5568').fontSize(10).text(`${page.errors} Errors | ${page.total_issues} Total Issues`);
        doc.moveDown(0.5);
    });

    doc.end();
}

module.exports = { generateExecutiveReport, generateCrawlReport };
