AWSTemplateFormatVersion: '2010-09-09'
Description: 'ADA Compliance Scanner - Client Environment (RDS + App Runner)'

Parameters:
  ClientName:
    Type: String
    Description: Name of the client (used for naming resources)
    AllowedPattern: "^[a-zA-Z0-9]+$"
  
  GitHubConnectionArn:
    Type: String
    Description: ARN of the App Runner GitHub Connection
  
  GitHubRepositoryUrl:
    Type: String
    Description: Repository URL
  
  GitHubBranch:
    Type: String
    Description: Branch to deploy
    Default: main

Resources:
  AppService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub "${ClientName}-ada-app"
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref GitHubConnectionArn
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: !Ref GitHubRepositoryUrl
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref GitHubBranch
          CodeConfiguration:
            ConfigurationSource: API
            CodeConfigurationValues:
              Runtime: NODEJS_18
              BuildCommand: "npm install"
              StartCommand: "node server.js"
              Port: "3000"
              RuntimeEnvironmentVariables:
                - Name: PORT
                  Value: "3000"
                - Name: SUPABASE_URL
                  Value: "https://dlfxpkixljqdiajantxy.supabase.co"
                - Name: SUPABASE_SERVICE_KEY
                  Value: "sb_secret_5GaJ-2asybNlcIurMObfyQ_lvwW7P5Y"

Outputs:
  ServiceUrl:
    Description: URL of the App Runner Service
    Value: !GetAtt AppService.ServiceUrl
